// This is an autogenerated file from running `firebase genkit:flow`.
'use server';

/**
 * @fileOverview This file defines a Genkit flow for categorizing expenses using AI.
 *
 * The flow takes an expense description as input and returns the predicted category.
 * It uses a pre-defined prompt and the Genkit AI to perform the categorization.
 *
 * @interface CategorizeExpenseInput - Defines the input schema for the categorizeExpense function.
 * @interface CategorizeExpenseOutput - Defines the output schema for the categorizeExpense function.
 * @function categorizeExpense - The main function to categorize an expense.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const CategorizeExpenseInputSchema = z.object({
  description: z
    .string()
    .describe('The description of the expense to categorize.'),
});
export type CategorizeExpenseInput = z.infer<typeof CategorizeExpenseInputSchema>;

const CategorizeExpenseOutputSchema = z.object({
  category: z
    .string()
    .describe('The predicted category of the expense (e.g., food, transportation, entertainment).'),
});
export type CategorizeExpenseOutput = z.infer<typeof CategorizeExpenseOutputSchema>;

/**
 * Categorizes an expense based on its description using AI.
 *
 * @param input - The input object containing the expense description.
 * @returns A promise that resolves to the categorized expense.
 */
export async function categorizeExpense(input: CategorizeExpenseInput): Promise<CategorizeExpenseOutput> {
  return categorizeExpenseFlow(input);
}

const categorizeExpensePrompt = ai.definePrompt({
  name: 'categorizeExpensePrompt',
  input: {
    schema: CategorizeExpenseInputSchema,
  },
  output: {
    schema: CategorizeExpenseOutputSchema,
  },
  prompt: `You are an expert financial advisor who categorizes expenses.

  Given the following expense description, determine the most appropriate category.

  Expense Description: {{{description}}}

  Possible categories: Food, Transportation, Entertainment, Utilities, Housing, Healthcare, Shopping, Travel, Education, Personal, Others

  Return only the category name.
  `,
});

const categorizeExpenseFlow = ai.defineFlow(
  {
    name: 'categorizeExpenseFlow',
    inputSchema: CategorizeExpenseInputSchema,
    outputSchema: CategorizeExpenseOutputSchema,
  },
  async input => {
    const {output} = await categorizeExpensePrompt(input);
    return output!;
  }
);
